name: Reparar Motor y Compilar
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Instalar Gradle Oficial
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.5
    - name: Generar Wrapper
      run: gradle wrapper
    - name: Compilar APK Ultra Liviano
      run: ./gradlew assembleDebug
    - name: Guardar APK Terminado
      uses: actions/upload-artifact@v4
      with:
        name: MudarMusica-Snaptube
        path: app/build/outputs/apk/debug/app-debug.apk
